config/routes.rb
Rails.application.routes.draw do
  resources :hashtags, only: [:index, :create, :destroy, :new]
  resources :tweets, only: [:index]
  root to: "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates_uniqueness_of :descricao, on: :create, message: "Já existe essa hashtag."
  validates_presence_of :descricao, on: :create, message: "O campo descrição é obrigatório."

  validate :no_space, on: :create
  validate :only_letters_and_digits, on: :create


  private
  def no_space
    unless (self.descricao =~ /[\s]/).nil?
      errors.add(:descricao, "Não é permitido usar espaços em branco em uma hashtag.")
    end
  end

  def only_letters_and_digits
    if self.descricao.size  != self.descricao.scan(/[\w\d]/).count
      errors.add(:descricao, "Uma hashtag deve conter apenas letras e números.")
    end
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates_uniqueness_of :tweet_id, on: :create, message: "Tweet já cadastrado."
 
  class << self
    def sync_twitter
      Hashtag.all.each do |hashtag|
        last_tweet_hashtag = Tweet::tweets_by_hashtags([hashtag]).last
        tweets = TwitterService.new(hashtag.descricao, last_tweet_hashtag.try(:twitter_id)).perform
        
        tweets.each do |tweet|
          
          new_tweet = Tweet.new
          new_tweet.tweet_id = tweet["id_str"]
          new_tweet.mensagem = tweet["full_text"]
          new_tweet.autor = tweet["user"]["screen_name"]
          new_tweet.data_publicacao = tweet["created_at"]
          new_tweet.hashtags = tweet["entities"]["hashtags"].map {|hashtag| hashtag["text"]}
          
          new_tweet.save
          
        end
      end
    end
    handle_asynchronously :sync_twitter
  end
    

  def self.tweets_by_hashtags(hashtags)
    if hashtags.present?
      hashtags = hashtags.map {|h| "'#{h.descricao.downcase}'" }.join(',')
    else
      hashtags = "''"
    end

    Tweet.where("array[#{hashtags}] && string_to_array(lower(array_to_string(hashtags, ',')),',')").order(data_publicacao: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def index
    @hashtags = Hashtag.all
  end

  def new
    @hashtag = Hashtag.new
  end

  def create
    @hashtag = Hashtag.new(resource_params)
    if @hashtag.save
      flash[:success] = "Hashtag criada com sucesso!"
      redirect_to hashtags_url
    else
      flash[:error] = @hashtag.errors.full_messages.join(' - ')
      render 'new'
    end
  end

  def destroy
    @hashtag = Hashtag.find(params[:id])
    if @hashtag.destroy
      flash[:success] = 'Hashtag deletada com sucesso!'
      redirect_to hashtags_url
    else
      flash[:error] = @hashtag.errors.full_messages.join(' - ')
      redirect_to hashtags_url
    end
  end

  private
  def resource_params
    params.require(:hashtag).permit(:descricao)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @options_hashtags = Hashtag.all

    if params[:hashtag].present?
      @hashtag = Hashtag.find(params[:hashtag])
      hashtags = [@hashtag]
    else
      hashtags = Hashtag.all
    end

    @tweets = Tweet::tweets_by_hashtags(hashtags).paginate(page: params[:page], per_page: 30)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hashtags/index.html.erb
<div class="card">
  <div class="card-header text-center">
    <h3>Lista de Hashtags</h3>
  </div>
  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th scope='col'>Hashtag</th>
          <th scope='col'></th>
        </tr>
      </thead>
      <tbody>
        <% @hashtags.each do |hashtag| %>
          <tr>
            <td><%= hashtag.descricao %></td>
            <td>
              <div class="float-right">
                <%= form_for hashtag, method: :delete do |f| %>
                  <button type='submit' class='btn btn-danger'>
                    Deletar
                  </button>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class='text-center'>
      <%= link_to "+ Nova Hashtag", new_hashtag_path, class: 'btn btn-success' %>
    </div>
    </div>
</div>

app/views/hashtags/new.html.erb
<div class="card">
  <div class="card-header text-center">
    <h3>Nova Hashtag</h3>
  </div>
  <div class="card-body">
    <%= form_for @hashtag do |f| %>
      <div class="form-group">
        <label>
          Descrição
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">#</span>
            </div>
            <%= f.text_field :descricao, class: "form-control", id: "hashtag", onkeyup: "hashtag_mask(this)" %>
          </div>

        </label>
      </div>
      <%= f.submit 'Criar Hashtag', class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Twitter Magrathea</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Hashtags
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%= new_hashtag_path %>">Criar Hashtag</a>
          <a class="dropdown-item" href="<%= hashtags_path %>">Lista de Hashtags</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= tweets_path %>">Tweets</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: '/layouts/menu' %>
    <% if flash.present? %>
      <div class="container col-4 offset-4">
        <div class="card flash text-center <%= flash.first[0] == 'error' ? 'bg-danger' : 'bg-success'%>">
          <% flash.each do |type, message|%>
            <div><%= message %></div>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="container col-8 offset-2">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/index.html.erb
<div class='container'>
  <div class='form-group col-6 offset-3'>
    <%= select_tag :hashtag, options_for_select(@options_hashtags.map{ |h| [h.descricao, h.id]}, @hashtag.try(:id)), {prompt: 'Selecionar Hashtag', class: 'form-control'} %></br>
  </div>
</div>
<div class="card">
  <div class="card-header text-center">
    <h3>Lista de Tweets</h3>
  </div>
  <div class="card-body">
    <div id='tweets'>
      <% @tweets.each do |tweet|%>
        <strong>Autor:</strong> <%= tweet.autor %></br>
        <strong>Mensagem:</strong> <%= tweet.mensagem %></br>
        <strong>Data de Publicação:</strong> <%= tweet.data_publicacao.strftime("%d/%m/%Y %H:%M:%S") %></br>
        <strong>Hashtags:</strong> <%= tweet.hashtags.join(' ') %>
        <hr>
      <% end %>
      <script>
        $('#hashtag').change(function(){
          window.location.href = '/tweets?hashtag=' + $(this).val();
        })
    
      </script>
      <%= will_paginate @tweets, previous_label: 'Anterior', next_label: 'Próximo' %>
    </div>
  </div>
</div>